#!/usr/bin/env bash
exec 2>&1

osascript -e "tell application \"Tunnelblick\"" -e "disconnect all" -e "end tell"

PIDS=$(ps aux | grep "Cisco Jabber" | grep -v "grep" | awk '{print $2}')
for pid in $PIDS; do
    kill $pid
done

# Execute TODOs for location
/Users/matteo/.locations/TODOs/Hotspot >> /tmp/Hotspot_TODO
