#!/usr/bin/env bash
exec 2>&1

PIDS=$(ps aux | grep "Cisco Jabber" | grep -v "grep")
for pid in $PIDS; do
    kill $pid
done

osascript -e "tell application \"Tunnelblick\"" -e "connect \"Germany\"" -e "end tell"
