#!/usr/bin/env bash
exec 2>&1

LOCATION="UNI"

# Kill jabber
#PIDS=$(ps aux | grep "Cisco Jabber" | grep -v "grep")
#for pid in $PIDS; do
#    kill $pid
#done

# Undergoing Webex Teams PoC
PIDS=$(ps aux | grep "Webex Teams" | grep -v "grep")
for pid in $PIDS; do
    kill $pid
done

osascript -e "tell application \"Tunnelblick\"" -e "connect \"Germany\"" -e "end tell"

# Execute TODOs for location
"$HOME/.scripts/run_todos" "$LOCATION"
